spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: 123
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
security:
  basic:
    enabled: false
management:
  health:
    redis:
      enabled: false