spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: 123
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
security:
  basic:
    enabled: true
management:
  health:
    redis:
      enabled: false


imooc:
  security:
    browser:
#      loginPage:
#        /demo-sigIn.html
      loginType: JSON
    code:
      image:
        length: 6
        width: 88
        url: /user/*
